name: openssl stable for windows

on: 
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/test.yml
    with:
      major: 3
      minor: 4
      patch: 0
      REPO_BRANCH: openssl-3.4.0
